version: '3.8'

services:
  auto-voc:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-voc:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - DATABASE_URL=postgres://vocmaster:vocmasterpassword@voc-db.cbeug4q2kw1j.eu-central-1.rds.amazonaws.com:5432/voc-db?sslmode=require
    restart: always
